name: goldwiser
favicon: null
layout_spectrum: 0.6761393807828426
typography_spectrum: 0.21984275756403804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20377672044560313
  lightness: 0.4750349847599864
  saturation: 0.1221754620783031
  rhythmicContrast: 0.3962240950204432
purpose: []
